"""Constants for the GTFS Realtime integration."""

DOMAIN = "gtfs_realtime"
API_KEY = "api_key"
GTFS_STATIC_DATA = "gtfs_static_data"
URL_ENDPOINTS = "url_endpoints"
ROUTE_ICONS = "route_icons"
STOP_ID = "stop_id"
ALERT_LIMIT = "alert_limit"
ARRIVAL_LIMIT = "arrival_limit"
ROUTE_ID = "route_id"
